
var ejs = require('ejs');
var fs = require('fs');
var _ = require('underscore');

var fields = {
    21: 'Code_BuildingVariant',
    22: 'Code_Building',
    23: 'Code_BuildingType',
    25: 'Code_ClimateRegion',
    26: 'Name_ClimateRegion',
    27: 'HeatingDays',
    28: 'Theta_e',
    29: 'I_Sol_Hor',
    30: 'I_Sol_East',
    31: 'I_Sol_South',
    32: 'I_Sol_West',
    33: 'I_Sol_North',
    35: 'Code_Measure_Roof_1',
    36: 'Code_Measure_Roof_2',
    37: 'Code_Measure_Wall_1',
    38: 'Code_Measure_Wall_2',
    39: 'Code_Measure_Wall_3',
    40: 'Code_Measure_Floor_1',
    41: 'Code_Measure_Floor_2',
    42: 'Code_Measure_Window_1',
    43: 'Code_Measure_Window_2',
    44: 'Code_Measure_Door_1',
    46: 'Code_MeasureType_Roof_1',
    47: 'Code_MeasureType_Roof_2',
    48: 'Code_MeasureType_Wall_1',
    49: 'Code_MeasureType_Wall_2',
    50: 'Code_MeasureType_Wall_3',
    51: 'Code_MeasureType_Floor_1',
    52: 'Code_MeasureType_Floor_2',
    53: 'Code_MeasureType_Window_1',
    54: 'Code_MeasureType_Window_2',
    55: 'Code_MeasureType_Door_1',
    57: 'g_gl_n',
    59: 'delta_U_ThermalBridging',
    60: 'theta_i',
    61: 'F_red_temp',
    62: 'n_air_infiltration',
    63: 'n_air_use',
    64: 'h_room',
    65: 'phi_int',
    66: 'F_sh_hor',
    67: 'F_sh_vert',
    68: 'F_f',
    69: 'F_w',
    70: 'c_m',
    82: 'Code_BuildingType',
    83: 'Year1_Building',
    84: 'Year2_Building',
    86: 'A_C_Ref',
    87: 'code_ThermalBridging',
    89: 'Code_Roof_1',
    90: 'Code_Roof_2',
    91: 'Code_Wall_1',
    92: 'Code_Wall_2',
    93: 'Code_Wall_3',
    94: 'Code_Floor_1',
    95: 'Code_Floor_2',
    96: 'Code_Window_1',
    97: 'Code_Window_2',
    98: 'Code_Door_1',
    100: 'U_Roof_1',
    101: 'U_Roof_2',
    102: 'U_Wall_1',
    103: 'U_Wall_2',
    104: 'U_Wall_3',
    105: 'U_Floor_1',
    106: 'U_Floor_2',
    107: 'U_Window_1',
    108: 'U_Window_2',
    109: 'U_Door_1',
    111: 'A_Roof_1',
    112: 'A_Roof_2',
    113: 'A_Wall_1',
    114: 'A_Wall_2',
    115: 'A_Wall_3',
    116: 'A_Floor_1',
    117: 'A_Floor_2',
    118: 'A_Window_1',
    119: 'A_Window_2',
    120: 'A_Door_1',
    122: 'A_Window_Horizontal',
    123: 'A_Window_East',
    124: 'A_Window_South',
    125: 'A_Window_West',
    126: 'A_Window_North',
    128: 'b_Transmission_Roof_1',
    129: 'b_Transmission_Roof_2',
    130: 'b_Transmission_Wall_1',
    131: 'b_Transmission_Wall_2',
    132: 'b_Transmission_Wall_3',
    133: 'b_Transmission_Floor_1',
    134: 'b_Transmission_Floor_2',
    143: 'U_Refurbished_Roof_1',
    144: 'U_Refurbished_Roof_2',
    145: 'U_Refurbished_Wall_1',
    146: 'U_Refurbished_Wall_2',
    147: 'U_Refurbished_Wall_3',
    148: 'U_Refurbished_Floor_1',
    149: 'U_Refurbished_Floor_2',
    150: 'U_Refurbished_Window_1',
    151: 'U_Refurbished_Window_2',
    152: 'U_Refurbished_Door_1',
    161: 'H_tr',
    162: 'H_ve',
    163: 'h_ht',
    164: 'Sum_DeltaT_for_HeatingDays',
    166: 'q_T_Roof_1',
    167: 'q_T_Roof_2',
    168: 'q_T_Wall_1',
    169: 'q_T_Wall_2',
    170: 'q_T_Wall_3',
    171: 'q_T_Floor_1',
    172: 'q_T_Floor_2',
    173: 'q_T_Window_1',
    174: 'q_T_Window_2',
    175: 'q_T_Door_1',
    177: 'q_T_ThermalBridging',
    179: 'q_tr',
    180: 'q_ve',
    181: 'q_sol',
    182: 'q_int',
    183: 'eta_h_gn',
    184: 'q_H_nd',
    186: 'q_T_Sum_Roof',
    187: 'q_T_Sum_Wall',
    188: 'q_T_Sum_Floor',
    189: 'q_T_Sum_Window'
};

for (var id in fields) {
    fields[id] = '<input id="'+fields[id]+'" name="'+fields[id]+'" type="text" />';
};

var base = [100, 46, 35, 143, 111];

var meaty_bit = {
    'Roof 1': _.flatten([base, 128, 'Result_Roof_1']),
    'Roof 2': _.flatten([base.map(function (x) { return x+1; }), 128+1, 'Result_Roof_2']),
    'Wall 1': _.flatten([base.map(function (x) { return x+2; }), 128+2, 'Result_Wall_1']),
    'Wall 2': _.flatten([base.map(function (x) { return x+3; }), 128+3, 'Result_Wall_2']),
    'Wall 3': _.flatten([base.map(function (x) { return x+4; }), 128+4, 'Result_Wall_3']),
    'Floor 1': _.flatten([base.map(function (x) { return x+5; }), 128+5, 'Result_Floor_1']),
    'Floor 2': _.flatten([base.map(function (x) { return x+6; }), 128+6, 'Result_Floor_2']),
    'Window 1': _.flatten([base.map(function (x) { return x+7; }),
                           '<input type="text" id="b_Transmission_Window_1" />',
                           'Result_Window_1']),
    'Window 2': _.flatten([base.map(function (x) { return x+8; }),
                           '<input type="text" id="b_Transmission_Window_2" />',
                           'Result_Window_2']),
    'Door 1': _.flatten([base.map(function (x) { return x+9; }),
                           '<input type="text" id="b_Transmission_Door_1" />',
                         'Result_Door_1'])
};

fs.readFile('./calcDemoBuildingProto.html',
            function (err, data) {

                var html = ejs.render(data+"",
                                      {locals: {
                                          fields: fields,
                                          meaty: meaty_bit,
                                          solar: ['Horizontal',
                                                  'East',
                                                  'South',
                                                  'West',
                                                  'North']
                                      }});
                fs.writeFile('./calcDemoBuilding.html', html);
});
